/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Logic.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author retr0
 */
public class ConsultaRevision extends javax.swing.JFrame {
    Counter counter;

    /**
     * Creates new form ConsultaRevision
     */
    public ConsultaRevision(Counter counter) {
        this.counter = counter;
        
        initComponents();
        if(counter.getClientes().size() != 0){
            String[] ids = new String[counter.getClientes().size()];
            for(int i = 0; i < counter.getClientes().size(); i++){
                ids[i] = counter.getClientes().get(i).getIdCliente();
            }
            cbxIDcliente.setModel(new javax.swing.DefaultComboBoxModel<>(ids));
        }       
       
        String[] idsCasillero = new String[counter.getCasilleros().size()];
        for(int i = 0; i < counter.getCasilleros().size(); i++){
            idsCasillero[i] = counter.getCasilleros().get(i).getIdCasillero();
        }
        cbxCasilleros.setModel(new javax.swing.DefaultComboBoxModel<>(idsCasillero));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaConsulta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cbxIDcliente = new javax.swing.JComboBox<>();
        cbxCasilleros = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de un casillero"));

        txaConsulta.setEditable(false);
        txaConsulta.setColumns(20);
        txaConsulta.setRows(5);
        jScrollPane1.setViewportView(txaConsulta);

        jLabel1.setText("Cliente:");

        cbxIDcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIDclienteActionPerformed(evt);
            }
        });

        cbxCasilleros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCasillerosActionPerformed(evt);
            }
        });

        jLabel2.setText("Casillero:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCasilleros, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCasilleros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCasillerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCasillerosActionPerformed
        // TODO add your handling code here:
        String id = (String)cbxCasilleros.getSelectedItem();
        txaConsulta.setText(counter.consultarCasillero(id));
    }//GEN-LAST:event_cbxCasillerosActionPerformed

    private void cbxIDclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIDclienteActionPerformed
        // TODO add your handling code here:
        String id = (String)cbxIDcliente.getSelectedItem();
        txaConsulta.setText(counter.consultarCasilleroCliente(id));
    }//GEN-LAST:event_cbxIDclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxCasilleros;
    private javax.swing.JComboBox<String> cbxIDcliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaConsulta;
    // End of variables declaration//GEN-END:variables
}
