/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Logic.*;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author retr0
 */
public class MenuFuncionalidades extends javax.swing.JFrame {

    Counter counter;
    ArrayList<String> listaHerramienta=new ArrayList<>();
    /**
     * Creates new form MenuFuncionalidades
     */
    public MenuFuncionalidades(Counter counter) {
        
        Date date = new Date();
        DateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String fechaActual = formato.format(date);
        setLocation(200,100);
        this.counter = counter;
        initComponents();
        String tipoDeCambio = "Valor \nDolar" + "\nCompra: " + this.counter.obtenerCompraDelTipoDeCambio(fechaActual) +
                "\nVenta:    " +this.counter.obtenerVentaDelTipoDeCambio(fechaActual);
        txaTipoDeCambio.setText(tipoDeCambio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdminisClient = new javax.swing.JPanel();
        btnRegistrarCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnConsultarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        lstClientes = new java.awt.List();
        lblNombreCliente = new javax.swing.JLabel();
        txfNombreCliente = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txfEmail = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txfTelefono = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txfDireccion = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        cbxAno = new javax.swing.JComboBox<>();
        lblMes = new javax.swing.JLabel();
        cbxMes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxDia = new javax.swing.JComboBox<>();
        pnlRetiroEntregables = new javax.swing.JPanel();
        lstEntregablesRetirables = new java.awt.List();
        btnCargarEntregablesPendientes = new javax.swing.JButton();
        btnAgregarCarrito = new javax.swing.JButton();
        lbImpuestoEntregablesPendientes = new javax.swing.JLabel();
        txtTotalImpuestoAPagar = new javax.swing.JTextField();
        selecVisa = new javax.swing.JRadioButton();
        selecMasCar = new javax.swing.JRadioButton();
        selecAmeExp = new javax.swing.JRadioButton();
        btnPagarEntregables = new javax.swing.JButton();
        lbTipoCliente = new javax.swing.JLabel();
        txtDescuentoTipoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTipoDeCambio = new javax.swing.JTextArea();
        selecEfectivo = new javax.swing.JRadioButton();
        txtImpuestoColones = new javax.swing.JTextField();
        pnlRecepcionEntregables = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTipoSobre = new javax.swing.JLabel();
        cbxTipoSobre = new javax.swing.JComboBox<>();
        lblPesoSobre = new javax.swing.JLabel();
        txfPesoSobre = new javax.swing.JTextField();
        lblGramosSobre = new javax.swing.JLabel();
        lblRemitenteSobre = new javax.swing.JLabel();
        txfRemitenteSobre = new javax.swing.JTextField();
        lblDescripcionSobre = new javax.swing.JLabel();
        txfDescripcionSobre = new javax.swing.JTextField();
        lblContenidoSobre = new javax.swing.JLabel();
        cbxContenidoSobre = new javax.swing.JComboBox<>();
        btnAgregarSobre = new javax.swing.JButton();
        btnCancelarSobre = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblContenidoPaquete = new javax.swing.JLabel();
        cbxContenidoPaquete = new javax.swing.JComboBox<>();
        rbtFragilPaquete = new javax.swing.JRadioButton();
        lblPesoPaquete = new javax.swing.JLabel();
        txfPesoPaquete = new javax.swing.JTextField();
        lblGramosPaquete = new javax.swing.JLabel();
        lblDescripcionPaquete = new javax.swing.JLabel();
        lblRemitentePaquete = new javax.swing.JLabel();
        txfRemitentePaquete = new javax.swing.JTextField();
        txfDescripcionPaquete = new javax.swing.JTextField();
        btnRegistrarPaquete = new javax.swing.JButton();
        btnCancelarPaquete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTemaRevista = new javax.swing.JLabel();
        rbtCatalogRevista = new javax.swing.JRadioButton();
        cbxContenidoRevista = new javax.swing.JComboBox<>();
        lblNombreRevista = new javax.swing.JLabel();
        txfNombreRevista = new javax.swing.JTextField();
        lblGramosPaquete1 = new javax.swing.JLabel();
        lblRemitenteRevista = new javax.swing.JLabel();
        txfRemitenteRevista = new javax.swing.JTextField();
        txfDescripcionRevista = new javax.swing.JTextField();
        lblDescripcionRevista = new javax.swing.JLabel();
        btnRegistrarRevista = new javax.swing.JButton();
        btnCancelarRevista = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblIDClientes = new javax.swing.JLabel();
        btnCargarIDClientes = new javax.swing.JButton();
        cbxIDClientes = new javax.swing.JComboBox<>();
        pnlConsultasDeArticulos = new javax.swing.JPanel();
        btnConsultaCasillero = new javax.swing.JButton();
        btnConsultarRecibidosUnaFecha = new javax.swing.JButton();
        btnConsultarEntregadosUnaFecha = new javax.swing.JButton();
        btnConsultaArticulosPendientes = new javax.swing.JButton();
        btnInformeContableDeUnDia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAdminisClient.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Clientes"));

        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        btnModificarCliente.setText("Modificar Cliente");
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });

        btnConsultarCliente.setText("Consultar Cliente");
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setText("Eliminar Cliente");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        lblNombreCliente.setText("Nombre: ");

        txfNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNombreClienteActionPerformed(evt);
            }
        });

        lblEmail.setText("Email: ");

        lblTelefono.setText("Teléfono: ");

        lblSexo.setText("Sexo: ");

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        jLabel1.setText("Fecha Nacimiento:");

        lblDireccion.setText("Dirección:");

        lblAno.setText("AAAA:");

        cbxAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));
        cbxAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAnoActionPerformed(evt);
            }
        });

        lblMes.setText("MM: ");

        cbxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMesActionPerformed(evt);
            }
        });

        jLabel2.setText("DD:");

        cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "30", "31" }));

        javax.swing.GroupLayout pnlAdminisClientLayout = new javax.swing.GroupLayout(pnlAdminisClient);
        pnlAdminisClient.setLayout(pnlAdminisClientLayout);
        pnlAdminisClientLayout.setHorizontalGroup(
            pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminisClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlAdminisClientLayout.createSequentialGroup()
                        .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(lblNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdminisClientLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfNombreCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminisClientLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdminisClientLayout.createSequentialGroup()
                                .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(pnlAdminisClientLayout.createSequentialGroup()
                                        .addComponent(lblSexo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlAdminisClientLayout.createSequentialGroup()
                                .addComponent(lblAno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlAdminisClientLayout.createSequentialGroup()
                        .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfDireccion))
                    .addGroup(pnlAdminisClientLayout.createSequentialGroup()
                        .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        pnlAdminisClientLayout.setVerticalGroup(
            pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminisClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lstClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCliente)
                    .addComponent(txfNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexo)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelefono)
                        .addComponent(txfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAno)
                        .addComponent(cbxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMes)
                        .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarCliente)
                    .addComponent(btnModificarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdminisClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarCliente)
                    .addComponent(btnEliminarCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRetiroEntregables.setBorder(javax.swing.BorderFactory.createTitledBorder("Retiro de entregables"));

        lstEntregablesRetirables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstEntregablesRetirablesActionPerformed(evt);
            }
        });

        btnCargarEntregablesPendientes.setText("Entregables Pendientes");
        btnCargarEntregablesPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarEntregablesPendientesActionPerformed(evt);
            }
        });

        btnAgregarCarrito.setText("Agregar al carrito");
        btnAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarritoActionPerformed(evt);
            }
        });

        lbImpuestoEntregablesPendientes.setText("Impuesto a pagar");

        txtTotalImpuestoAPagar.setEditable(false);
        txtTotalImpuestoAPagar.setText("$0");

        selecVisa.setText("Visa");
        selecVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecVisaActionPerformed(evt);
            }
        });

        selecMasCar.setText("Master Card");

        selecAmeExp.setText("American Express");

        btnPagarEntregables.setText("Pagar");
        btnPagarEntregables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarEntregablesActionPerformed(evt);
            }
        });

        lbTipoCliente.setText("Descuento por Tipo Cliente");

        txtDescuentoTipoCliente.setEditable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);

        txaTipoDeCambio.setEditable(false);
        txaTipoDeCambio.setColumns(20);
        txaTipoDeCambio.setRows(5);
        jScrollPane1.setViewportView(txaTipoDeCambio);

        selecEfectivo.setText("Efectivo");

        txtImpuestoColones.setEditable(false);
        txtImpuestoColones.setText("₡0");

        javax.swing.GroupLayout pnlRetiroEntregablesLayout = new javax.swing.GroupLayout(pnlRetiroEntregables);
        pnlRetiroEntregables.setLayout(pnlRetiroEntregablesLayout);
        pnlRetiroEntregablesLayout.setHorizontalGroup(
            pnlRetiroEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRetiroEntregablesLayout.createSequentialGroup()
                .addGroup(pnlRetiroEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRetiroEntregablesLayout.createSequentialGroup()
                        .addComponent(lbImpuestoEntregablesPendientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalImpuestoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImpuestoColones))
                    .addComponent(lstEntregablesRetirables, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRetiroEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRetiroEntregablesLayout.createSequentialGroup()
                        .addComponent(lbTipoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescuentoTipoCliente))
                    .addGroup(pnlRetiroEntregablesLayout.createSequentialGroup()
                        .addGroup(pnlRetiroEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecVisa)
                            .addComponent(selecMasCar)
                            .addComponent(selecAmeExp)
                            .addComponent(selecEfectivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRetiroEntregablesLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnPagarEntregables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlRetiroEntregablesLayout.createSequentialGroup()
                        .addGroup(pnlRetiroEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarCarrito)
                            .addComponent(btnCargarEntregablesPendientes))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlRetiroEntregablesLayout.setVerticalGroup(
            pnlRetiroEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRetiroEntregablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRetiroEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRetiroEntregablesLayout.createSequentialGroup()
                        .addGroup(pnlRetiroEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlRetiroEntregablesLayout.createSequentialGroup()
                                .addComponent(selecEfectivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selecVisa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selecMasCar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selecAmeExp))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(btnAgregarCarrito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCargarEntregablesPendientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(pnlRetiroEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTipoCliente)
                            .addComponent(txtDescuentoTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lstEntregablesRetirables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRetiroEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbImpuestoEntregablesPendientes)
                    .addComponent(txtTotalImpuestoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagarEntregables)
                    .addComponent(txtImpuestoColones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        pnlRecepcionEntregables.setBorder(javax.swing.BorderFactory.createTitledBorder("Recepcion de Entregables"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Sobre"));

        lblTipoSobre.setText("Tipo:");

        cbxTipoSobre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aereo", "Manila" }));

        lblPesoSobre.setText("Peso:");

        txfPesoSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPesoSobreActionPerformed(evt);
            }
        });

        lblGramosSobre.setText("gramos");

        lblRemitenteSobre.setText("Remitente: ");

        lblDescripcionSobre.setText("Descripcion:");

        lblContenidoSobre.setText("Contenido:");

        cbxContenidoSobre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Documentacion", "Articulo Pequeño" }));

        btnAgregarSobre.setText("Registrar");
        btnAgregarSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSobreActionPerformed(evt);
            }
        });

        btnCancelarSobre.setText("Cancelar");
        btnCancelarSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarSobreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTipoSobre)
                                .addGap(18, 18, 18)
                                .addComponent(cbxTipoSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPesoSobre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfPesoSobre)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblGramosSobre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblContenidoSobre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxContenidoSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcionSobre)
                            .addComponent(lblRemitenteSobre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfRemitenteSobre)
                            .addComponent(txfDescripcionSobre))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnCancelarSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoSobre)
                    .addComponent(cbxTipoSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContenidoSobre)
                    .addComponent(cbxContenidoSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfPesoSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGramosSobre))
                    .addComponent(lblPesoSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfRemitenteSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemitenteSobre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcionSobre)
                    .addComponent(txfDescripcionSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarSobre)
                    .addComponent(btnCancelarSobre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Paquete"));

        lblContenidoPaquete.setText("Contenido:");

        cbxContenidoPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Juguetes", "Libros", "Electronico", "Herramientas", "Joyeria" }));
        cbxContenidoPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxContenidoPaqueteActionPerformed(evt);
            }
        });

        rbtFragilPaquete.setText("Fragil");
        rbtFragilPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFragilPaqueteActionPerformed(evt);
            }
        });

        lblPesoPaquete.setText("Peso:");

        txfPesoPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPesoPaqueteActionPerformed(evt);
            }
        });

        lblGramosPaquete.setText("gramos");

        lblDescripcionPaquete.setText("Descripcion:");

        lblRemitentePaquete.setText("Remitente: ");

        txfDescripcionPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDescripcionPaqueteActionPerformed(evt);
            }
        });

        btnRegistrarPaquete.setText("Registrar");
        btnRegistrarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPaqueteActionPerformed(evt);
            }
        });

        btnCancelarPaquete.setText("Cancelar");
        btnCancelarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPaqueteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblContenidoPaquete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxContenidoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRemitentePaquete)
                            .addComponent(lblDescripcionPaquete))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfRemitentePaquete, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txfDescripcionPaquete)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPesoPaquete)
                        .addGap(12, 12, 12)
                        .addComponent(txfPesoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGramosPaquete)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(rbtFragilPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarPaquete, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(btnCancelarPaquete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContenidoPaquete)
                            .addComponent(cbxContenidoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtFragilPaquete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPesoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfPesoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGramosPaquete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfRemitentePaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRemitentePaquete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescripcionPaquete)
                            .addComponent(txfDescripcionPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnRegistrarPaquete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarPaquete)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Revista"));

        lblTemaRevista.setText("Tema:");

        rbtCatalogRevista.setText("Catalogo");
        rbtCatalogRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCatalogRevistaActionPerformed(evt);
            }
        });

        cbxContenidoRevista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Noticias", "Belleza/Moda", "Tecnologia", "Salud/ medicina", "Cocina", "Otros", " " }));
        cbxContenidoRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxContenidoRevistaActionPerformed(evt);
            }
        });

        lblNombreRevista.setText("Nombre:");

        txfNombreRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNombreRevistaActionPerformed(evt);
            }
        });

        lblRemitenteRevista.setText("Remitente: ");

        txfDescripcionRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDescripcionRevistaActionPerformed(evt);
            }
        });

        lblDescripcionRevista.setText("Descripcion:");

        btnRegistrarRevista.setText("Registrar");
        btnRegistrarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRevistaActionPerformed(evt);
            }
        });

        btnCancelarRevista.setText("Cancelar");
        btnCancelarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRevistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRemitenteRevista)
                            .addComponent(lblDescripcionRevista))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfRemitenteRevista)
                            .addComponent(txfDescripcionRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNombreRevista)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(lblGramosPaquete1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(txfNombreRevista))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTemaRevista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxContenidoRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(rbtCatalogRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarRevista, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(btnCancelarRevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtCatalogRevista)
                            .addComponent(lblNombreRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfNombreRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTemaRevista)
                                    .addComponent(cbxContenidoRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfRemitenteRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRemitenteRevista))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDescripcionRevista)
                                    .addComponent(txfDescripcionRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblGramosPaquete1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnRegistrarRevista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarRevista)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el id"));

        lblIDClientes.setText("ID:");

        btnCargarIDClientes.setText("Cargar ID's");
        btnCargarIDClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarIDClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblIDClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxIDClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCargarIDClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDClientes)
                    .addComponent(cbxIDClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnCargarIDClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRecepcionEntregablesLayout = new javax.swing.GroupLayout(pnlRecepcionEntregables);
        pnlRecepcionEntregables.setLayout(pnlRecepcionEntregablesLayout);
        pnlRecepcionEntregablesLayout.setHorizontalGroup(
            pnlRecepcionEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecepcionEntregablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecepcionEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlRecepcionEntregablesLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlRecepcionEntregablesLayout.setVerticalGroup(
            pnlRecepcionEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecepcionEntregablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecepcionEntregablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlConsultasDeArticulos.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de artículos"));

        btnConsultaCasillero.setText("Consultar casillero");
        btnConsultaCasillero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCasilleroActionPerformed(evt);
            }
        });

        btnConsultarRecibidosUnaFecha.setText("Paquetes recibidos en una fecha");
        btnConsultarRecibidosUnaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarRecibidosUnaFechaActionPerformed(evt);
            }
        });

        btnConsultarEntregadosUnaFecha.setText("Paquetes entregados en una fecha");
        btnConsultarEntregadosUnaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEntregadosUnaFechaActionPerformed(evt);
            }
        });

        btnConsultaArticulosPendientes.setText("Articulos Pendientes");
        btnConsultaArticulosPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaArticulosPendientesActionPerformed(evt);
            }
        });

        btnInformeContableDeUnDia.setText("Informe contable de una fecha");
        btnInformeContableDeUnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeContableDeUnDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultasDeArticulosLayout = new javax.swing.GroupLayout(pnlConsultasDeArticulos);
        pnlConsultasDeArticulos.setLayout(pnlConsultasDeArticulosLayout);
        pnlConsultasDeArticulosLayout.setHorizontalGroup(
            pnlConsultasDeArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasDeArticulosLayout.createSequentialGroup()
                .addGroup(pnlConsultasDeArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultasDeArticulosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlConsultasDeArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnConsultaCasillero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarEntregadosUnaFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlConsultasDeArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnConsultarRecibidosUnaFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(btnConsultaArticulosPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlConsultasDeArticulosLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnInformeContableDeUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConsultasDeArticulosLayout.setVerticalGroup(
            pnlConsultasDeArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasDeArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultasDeArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultaCasillero, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnConsultarRecibidosUnaFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultasDeArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarEntregadosUnaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultaArticulosPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInformeContableDeUnDia, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAdminisClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlRetiroEntregables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRecepcionEntregables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConsultasDeArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlRecepcionEntregables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlConsultasDeArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlAdminisClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlRetiroEntregables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNombreClienteActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        if(txfNombreCliente.getText().equals("") || txfDireccion.getText().equals("") || txfTelefono.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Uno o varias entradas estan vacias", "Error", 1);
        }
        else{
            String nombre = txfNombreCliente.getText();
            String direccion = txfDireccion.getText();
            String fecha = (String)cbxAno.getSelectedItem() + "/" + (String)cbxMes.getSelectedItem() + "/" + (String)cbxDia.getSelectedItem();
            String telefono = txfTelefono.getText();
            String sexo = (String)cbxSexo.getSelectedItem();
            String correo = txfEmail.getText();
            if (!isValidEmail(correo)){
                JOptionPane.showMessageDialog(this, "El correo no tiene un formato adecuado", "Error", 1);
            }
            else if(telefono.length() != 8 || !isInteger(telefono)){
                JOptionPane.showMessageDialog(this, "El numero de telefono no tiene un formato adecuado", "Error", 1);
            }
            else if(!isPosibleToInsert()){
                JOptionPane.showMessageDialog(this, "Ya no hay casilleros disponible", "Error", 1);
            }
            else{
                Casillero siguienteLibre = counter.getCasilleroLibre();
                Cliente aInsertar = new Cliente(nombre, correo, telefono, direccion, sexo, fecha, siguienteLibre);
                siguienteLibre.setEstado(true);
                siguienteLibre.setCliente(aInsertar);
                counter.getClientes().add(aInsertar);
                lstClientes.add(aInsertar.toLst());
                txfDireccion.setText("");
                txfEmail.setText("");
                txfNombreCliente.setText("");
                txfTelefono.setText("");
            }
        }
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void cbxAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAnoActionPerformed
        if(cbxMes.getSelectedItem().equals("01") || cbxMes.getSelectedItem().equals("03") || cbxMes.getSelectedItem().equals("05") || cbxMes.getSelectedItem().equals("07") || cbxMes.getSelectedItem().equals("08") || cbxMes.getSelectedItem().equals("10") || cbxMes.getSelectedItem().equals("12")){
            cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        }
        else if(isBisiesto(Integer.parseInt((String)cbxAno.getSelectedItem())) && cbxMes.getSelectedItem().equals("02")){
            cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"}));
        }
        else if(!isBisiesto(Integer.parseInt((String)cbxAno.getSelectedItem())) && cbxMes.getSelectedItem().equals("02")){
            cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28"}));
        }
        else{
            cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"}));
        }
    }//GEN-LAST:event_cbxAnoActionPerformed

    private void cbxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMesActionPerformed
        // TODO add your handling code here:
        if(cbxMes.getSelectedItem().equals("01") || cbxMes.getSelectedItem().equals("03") || cbxMes.getSelectedItem().equals("05") || cbxMes.getSelectedItem().equals("07") || cbxMes.getSelectedItem().equals("08") || cbxMes.getSelectedItem().equals("10") || cbxMes.getSelectedItem().equals("12")){
            cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        }
        else if(isBisiesto(Integer.parseInt((String)cbxAno.getSelectedItem())) && cbxMes.getSelectedItem().equals("02")){
            cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"}));
        }
        else if(!isBisiesto(Integer.parseInt((String)cbxAno.getSelectedItem())) && cbxMes.getSelectedItem().equals("02")){
            cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28"}));
        }
        else{
            cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"}));
        }
    }//GEN-LAST:event_cbxMesActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        if(lstClientes.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente de la lista", "Error", 1);
        }
        else{
            int index = lstClientes.getSelectedIndex();
            for (int i = 0; i <= index; i++){
                if(i == index){
                    lstClientes.delItem(i);
                    counter.getClientes().remove(i);
                    counter.getCasilleros().get(i).setEstado(false);
                }
            }
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        // TODO add your handling code here:
        if(lstClientes.getSelectedIndex() != -1){
            String nombre = "";
            String id = "";
            String datos = "";
            for(int i = 0; i <= lstClientes.getSelectedIndex(); i++){
                if(i == lstClientes.getSelectedIndex()){
                    nombre = counter.getClientes().get(i).getNombre();
                    id = counter.getClientes().get(i).getIdCliente();
                    datos = counter.getClientes().get(i).toString();
                }
            }
            ConsultarCliente ventana = new ConsultarCliente(nombre, id, datos);
            ventana.show(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente de la lista", "Error", 1);
        }
    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        // TODO add your handling code here:
        ModificarCliente ventana = new ModificarCliente(counter.getClientes(), lstClientes);
        ventana.show(true);
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void txfPesoSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPesoSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPesoSobreActionPerformed

    private void btnCancelarSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarSobreActionPerformed
        // TODO add your handling code here:
        txfPesoSobre.setText("");
        txfDescripcionSobre.setText("");
        txfRemitenteSobre.setText("");
    }//GEN-LAST:event_btnCancelarSobreActionPerformed

    private void btnAgregarSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSobreActionPerformed
        // TODO add your handling code here:
        if(txfPesoSobre.getText().equals("") || txfDescripcionSobre.getText().equals("") || txfRemitenteSobre.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Uno o varios espacios estan vacios", "Error", 1);
        }
        else if(!isDouble(txfPesoSobre.getText())){
            JOptionPane.showMessageDialog(this, "Formato del peso no es correcto", "Error", 1);
        }
        else if(cbxIDClientes.getItemCount() == 0){
            JOptionPane.showMessageDialog(this, "Seleccione un id de cliente destino", "Error", 1);
        }
        else{
            String tipo = (String)cbxTipoSobre.getSelectedItem();
            String contenido = (String)cbxContenidoSobre.getSelectedItem();
            double peso = Double.parseDouble(txfPesoSobre.getText());
            String codReferencia = Integer.toString(counter.getCantidadEntregables(), 16);
            boolean estado = false;
            String descripcion = txfDescripcionSobre.getText();
            String remitente = txfRemitenteSobre.getText();
            String idCliente = (String)cbxIDClientes.getSelectedItem();
            Sobre nuevo = new Sobre(tipo, contenido, peso, codReferencia, estado, descripcion, remitente);
            counter.recibirArticulo(nuevo, idCliente);
            txfPesoSobre.setText("");
            txfDescripcionSobre.setText("");
            txfRemitenteSobre.setText("");
            JOptionPane.showMessageDialog(this, "Se ha registrado con exito al casillero", "Notificacion", 1);   
        }
    }//GEN-LAST:event_btnAgregarSobreActionPerformed

    private void btnCargarIDClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarIDClientesActionPerformed
        // TODO add your handling code here:
        if(counter.getClientes().size() != 0){
            String[] ids = new String[counter.getClientes().size()];
            for(int i = 0; i < counter.getClientes().size(); i++){
                ids[i] = counter.getClientes().get(i).getIdCliente();
            }
            cbxIDClientes.setModel(new javax.swing.DefaultComboBoxModel<>(ids));
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe insertar clientes", "Error", 1);
        }
    }//GEN-LAST:event_btnCargarIDClientesActionPerformed

    private void cbxContenidoPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxContenidoPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxContenidoPaqueteActionPerformed

    private void rbtFragilPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFragilPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtFragilPaqueteActionPerformed

    private void txfPesoPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPesoPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPesoPaqueteActionPerformed

    private void txfDescripcionPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDescripcionPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDescripcionPaqueteActionPerformed

    private void btnRegistrarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPaqueteActionPerformed
        // TODO add your handling code here:
        if(txfPesoPaquete.getText().equals("") || txfDescripcionPaquete.getText().equals("") || txfRemitentePaquete.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Uno o varios espacios estan vacios", "Error", 1);
        }
        else if(!isDouble(txfPesoPaquete.getText())){
            JOptionPane.showMessageDialog(this, "Formato del peso no es correcto", "Error", 1);
        }
        else if(cbxIDClientes.getItemCount() == 0){
            JOptionPane.showMessageDialog(this, "Seleccione un id de cliente destino", "Error", 1);
        }
        else{
            String contenido = (String)cbxContenidoPaquete.getSelectedItem();
            double peso = Double.parseDouble(txfPesoPaquete.getText());
            String codReferencia = Integer.toString(counter.getCantidadEntregables(), 16);
            boolean estado = false;
            boolean fragil = rbtFragilPaquete.isSelected();
            String descripcion = txfDescripcionPaquete.getText();
            String remitente = txfRemitentePaquete.getText();
            String idCliente = (String)cbxIDClientes.getSelectedItem();
            Paquete nuevo = new Paquete(contenido, fragil, peso, codReferencia, estado, descripcion, remitente);
            counter.recibirArticulo(nuevo, idCliente);
            txfPesoPaquete.setText("");
            txfDescripcionPaquete.setText("");
            txfRemitentePaquete.setText("");
            rbtFragilPaquete.setSelected(false);
            JOptionPane.showMessageDialog(this, "Se ha registrado con exito al casillero", "Notificacion", 1);   
        }
    }//GEN-LAST:event_btnRegistrarPaqueteActionPerformed

    private void btnCancelarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPaqueteActionPerformed
        // TODO add your handling code here:
        txfPesoPaquete.setText("");
        txfDescripcionPaquete.setText("");
        txfRemitentePaquete.setText("");
        rbtFragilPaquete.setSelected(false);
    }//GEN-LAST:event_btnCancelarPaqueteActionPerformed

    private void rbtCatalogRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCatalogRevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtCatalogRevistaActionPerformed

    private void cbxContenidoRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxContenidoRevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxContenidoRevistaActionPerformed

    private void txfNombreRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreRevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNombreRevistaActionPerformed

    private void txfDescripcionRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDescripcionRevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDescripcionRevistaActionPerformed

    private void btnRegistrarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRevistaActionPerformed
        if(txfNombreRevista.getText().equals("") || txfDescripcionRevista.getText().equals("") || txfRemitenteRevista.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Uno o varios espacios estan vacios", "Error", 1);
        }
        else if(cbxIDClientes.getItemCount() == 0){
            JOptionPane.showMessageDialog(this, "Seleccione un id de cliente destino", "Error", 1);
        }
        else{
            String nombre = txfNombreRevista.getText();
            String tema = (String)cbxContenidoRevista.getSelectedItem();
            String codReferencia = Integer.toString(counter.getCantidadEntregables(), 16);
            boolean estado = false;
            boolean catalogo = rbtCatalogRevista.isSelected();
            String descripcion = txfDescripcionRevista.getText();
            String remitente = txfRemitentePaquete.getText();
            String idCliente = (String)cbxIDClientes.getSelectedItem();
            Revista nuevo = new Revista(nombre, catalogo, tema, codReferencia, estado, descripcion, remitente);
            counter.recibirArticulo(nuevo, idCliente);
            txfNombreRevista.setText("");
            txfDescripcionRevista.setText("");
            txfRemitenteRevista.setText("");
            rbtCatalogRevista.setSelected(false);
            JOptionPane.showMessageDialog(this, "Se ha registrado con exito al casillero", "Notificacion", 1);   
        }
    }//GEN-LAST:event_btnRegistrarRevistaActionPerformed

    private void btnCancelarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRevistaActionPerformed
        // TODO add your handling code here:
        txfNombreRevista.setText("");
            txfDescripcionRevista.setText("");
            txfRemitenteRevista.setText("");
            rbtCatalogRevista.setSelected(false);
    }//GEN-LAST:event_btnCancelarRevistaActionPerformed

    private void btnConsultaCasilleroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCasilleroActionPerformed
        // TODO add your handling code here:
        if(counter.getClientes().size() > 0){
            ConsultaRevision nueva = new ConsultaRevision(counter);
            nueva.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe insertar clientes", "Error", 1);
        }
    }//GEN-LAST:event_btnConsultaCasilleroActionPerformed

    private void btnConsultarRecibidosUnaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarRecibidosUnaFechaActionPerformed
        // TODO add your handling code here:
        ConsultaPaquetesRecibidosFecha nueva = new ConsultaPaquetesRecibidosFecha(counter);
        nueva.setVisible(true);
    }//GEN-LAST:event_btnConsultarRecibidosUnaFechaActionPerformed

    private void btnConsultarEntregadosUnaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEntregadosUnaFechaActionPerformed
        // TODO add your handling code here:
        ConsultarPaquetesEntregadosFecha nueva = new ConsultarPaquetesEntregadosFecha(counter);
        nueva.setVisible(true);
    }//GEN-LAST:event_btnConsultarEntregadosUnaFechaActionPerformed

    private void btnConsultaArticulosPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaArticulosPendientesActionPerformed
        // TODO add your handling code here:
        ConsultaDeFaltantesPorRetirar nuevo = new ConsultaDeFaltantesPorRetirar(counter);
        nuevo.setVisible(true);
    }//GEN-LAST:event_btnConsultaArticulosPendientesActionPerformed

    private void btnCargarEntregablesPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarEntregablesPendientesActionPerformed
        if(lstClientes.getSelectedIndex() != -1){
            String id = "";
            for(int i = 0; i <= lstClientes.getSelectedIndex(); i++){
                if(i == lstClientes.getSelectedIndex()){
                    id = counter.getClientes().get(i).getIdCliente();
                    break;
                }
            }
            cargarPendientesCliente(id);
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente de la lista", "Error", 1);
        }
    }//GEN-LAST:event_btnCargarEntregablesPendientesActionPerformed

    private void lstEntregablesRetirablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstEntregablesRetirablesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstEntregablesRetirablesActionPerformed

    private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarritoActionPerformed
        if(lstEntregablesRetirables.getSelectedIndex() != -1){
            double total=Double.valueOf(txtTotalImpuestoAPagar.getText().substring(1,txtTotalImpuestoAPagar.getText().length()));
            String entregableS=lstEntregablesRetirables.getSelectedItem();
            double impuesto=Double.valueOf(entregableS.substring(entregableS.indexOf("Impuesto: ")+10
                    ,entregableS.length()));
            total+=impuesto;
            txtTotalImpuestoAPagar.setText("$"+String.valueOf(total));
            Date date=new Date();
            DateFormat formato=new SimpleDateFormat("dd/MM/YYYY");
            txtImpuestoColones.setText("₡"+String.valueOf(total * counter.obtenerCompraDelTipoDeCambio(formato.format(date))).substring(0,8));
            listaHerramienta.add(entregableS.substring(entregableS.indexOf("go: ")+4,
                    entregableS.indexOf(";")));
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un entregable de la lista", "Error", 1);
        }
    }//GEN-LAST:event_btnAgregarCarritoActionPerformed

    private void btnPagarEntregablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarEntregablesActionPerformed
        if("$0".equals(txtTotalImpuestoAPagar.getText())){
            JOptionPane.showMessageDialog(this, "No ha selecionado ningun entregable", "Error", 1);
        }else{
            if((selecVisa.isSelected()&&!selecMasCar.isSelected()&&!selecAmeExp.isSelected()&&!selecEfectivo.isSelected())
                    ||(!selecVisa.isSelected()&&selecMasCar.isSelected()&&!selecAmeExp.isSelected()&&!selecEfectivo.isSelected())
                    ||(!selecVisa.isSelected()&&!selecMasCar.isSelected()&&selecAmeExp.isSelected()&&!selecEfectivo.isSelected())
                    ||(!selecVisa.isSelected()&&!selecMasCar.isSelected()&&!selecAmeExp.isSelected()&&selecEfectivo.isSelected())){
                String idCasillero=listaHerramienta.get(0);
                listaHerramienta.remove(0);
                for(Casillero casillero:counter.getCasilleros()){
                    if(casillero.getIdCasillero().equals(idCasillero)){
                        for(String s:listaHerramienta){
                            for(Entregable entregable:casillero.getEntregables()){
                                if(entregable.getCodReferencia().equals(s)){
                                    entregable.entregar();
                                }
                            }
                        }
                        listaHerramienta.clear();
                        txtDescuentoTipoCliente.setText("0");
                        cargarPendientesCliente(casillero.getCliente().getIdCliente());
                        break;
                    }
                }
                double total=Double.valueOf(txtTotalImpuestoAPagar.getText().substring(1));
                String descuentoS=txtDescuentoTipoCliente.getText();
                if(!"0%".equals(descuentoS)){
                    double descuento=Double.valueOf(descuentoS.substring(0, 2))/100;
                    descuentoS=String.valueOf(total*descuento);
                    JOptionPane.showMessageDialog(this, descuentoS+" pagado con el descuento aplicado", "Pagado", 1);
                }else{
                    JOptionPane.showMessageDialog(this, "impuesto pagado correctamente, no descuento aplicado", "Pagado", 1);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Elija solo una opción de pago", "Error", 1);
            }
        }
    }//GEN-LAST:event_btnPagarEntregablesActionPerformed

    private void selecVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecVisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecVisaActionPerformed

    private void btnInformeContableDeUnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeContableDeUnDiaActionPerformed
        // TODO add your handling code here:
        InformeContableDeUnaFecha nueva = new InformeContableDeUnaFecha(counter);
        nueva.setVisible(true);
    }//GEN-LAST:event_btnInformeContableDeUnDiaActionPerformed

    private void cargarPendientesCliente(String id){
        lstEntregablesRetirables.clear();
        Cliente client = null;
        for(Cliente cliente:counter.getClientes()){
            if(cliente.getIdCliente().equals(id)){
                client=cliente;
                break;
            }
        }
        if(client.getTipo()==Tipo.PLATA){
            txtDescuentoTipoCliente.setText("5%");
        }else if(client.getTipo()==Tipo.ORO){
            txtDescuentoTipoCliente.setText("10%");
        }else{
            txtDescuentoTipoCliente.setText("0%");
        }
        txtTotalImpuestoAPagar.setText("$0");
        txtImpuestoColones.setText("₡0");
        listaHerramienta.clear();
        listaHerramienta.add(client.getCasillero().getIdCasillero());
        for(Entregable entregable:client.getCasillero().getEntregables()){
            if(!entregable.isEstadoEntrega()){
                lstEntregablesRetirables.add(entregable.toList());
            }
        }
    }
    /**
     * 
     * @param anio
     * @return metodo de validacion para el bisiesto
     */
    private boolean isBisiesto(int anio){
        if((anio % 4 == 0) && ((anio % 100 != 0) || (anio % 400 == 0))){
            return true;
        }
        else{
            return false;
        }
    }
    
    /**
     * 
     * @param email
     * @return valida el email
     */
    private boolean isValidEmail(String email){
         // Patrón para validar el email
        Pattern pattern = Pattern
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(email);
 
        if (mather.find() == true) {
            return true;
        } else {
            return false;
        }
    }
    
    /**
     * 
     * @return si es posible insertar
     */
    private boolean isPosibleToInsert(){
        if(counter.getClientes().size() != counter.getCantidadCasilleros()){
            return true;
        }
        else{
            return false;
        }
    }
    
    private boolean isInteger(String numero){
        try{
            Integer.parseInt(numero);
            return true;
        }catch(NumberFormatException e){
            return false;
        }
    }
    
    private boolean isDouble(String numero){
        try{
            Double.parseDouble(numero);
            return true;
        }catch(NumberFormatException e){
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JButton btnAgregarSobre;
    private javax.swing.JButton btnCancelarPaquete;
    private javax.swing.JButton btnCancelarRevista;
    private javax.swing.JButton btnCancelarSobre;
    private javax.swing.JButton btnCargarEntregablesPendientes;
    private javax.swing.JButton btnCargarIDClientes;
    private javax.swing.JButton btnConsultaArticulosPendientes;
    private javax.swing.JButton btnConsultaCasillero;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarEntregadosUnaFecha;
    private javax.swing.JButton btnConsultarRecibidosUnaFecha;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnInformeContableDeUnDia;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnPagarEntregables;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegistrarPaquete;
    private javax.swing.JButton btnRegistrarRevista;
    private javax.swing.JComboBox<String> cbxAno;
    private javax.swing.JComboBox<String> cbxContenidoPaquete;
    private javax.swing.JComboBox<String> cbxContenidoRevista;
    private javax.swing.JComboBox<String> cbxContenidoSobre;
    private javax.swing.JComboBox<String> cbxDia;
    private javax.swing.JComboBox<String> cbxIDClientes;
    private javax.swing.JComboBox<String> cbxMes;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> cbxTipoSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbImpuestoEntregablesPendientes;
    private javax.swing.JLabel lbTipoCliente;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblContenidoPaquete;
    private javax.swing.JLabel lblContenidoSobre;
    private javax.swing.JLabel lblDescripcionPaquete;
    private javax.swing.JLabel lblDescripcionRevista;
    private javax.swing.JLabel lblDescripcionSobre;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGramosPaquete;
    private javax.swing.JLabel lblGramosPaquete1;
    private javax.swing.JLabel lblGramosSobre;
    private javax.swing.JLabel lblIDClientes;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreRevista;
    private javax.swing.JLabel lblPesoPaquete;
    private javax.swing.JLabel lblPesoSobre;
    private javax.swing.JLabel lblRemitentePaquete;
    private javax.swing.JLabel lblRemitenteRevista;
    private javax.swing.JLabel lblRemitenteSobre;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTemaRevista;
    private javax.swing.JLabel lblTipoSobre;
    private java.awt.List lstClientes;
    private java.awt.List lstEntregablesRetirables;
    private javax.swing.JPanel pnlAdminisClient;
    private javax.swing.JPanel pnlConsultasDeArticulos;
    private javax.swing.JPanel pnlRecepcionEntregables;
    private javax.swing.JPanel pnlRetiroEntregables;
    private javax.swing.JRadioButton rbtCatalogRevista;
    private javax.swing.JRadioButton rbtFragilPaquete;
    private javax.swing.JRadioButton selecAmeExp;
    private javax.swing.JRadioButton selecEfectivo;
    private javax.swing.JRadioButton selecMasCar;
    private javax.swing.JRadioButton selecVisa;
    private javax.swing.JTextArea txaTipoDeCambio;
    private javax.swing.JTextField txfDescripcionPaquete;
    private javax.swing.JTextField txfDescripcionRevista;
    private javax.swing.JTextField txfDescripcionSobre;
    private javax.swing.JTextField txfDireccion;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfNombreCliente;
    private javax.swing.JTextField txfNombreRevista;
    private javax.swing.JTextField txfPesoPaquete;
    private javax.swing.JTextField txfPesoSobre;
    private javax.swing.JTextField txfRemitentePaquete;
    private javax.swing.JTextField txfRemitenteRevista;
    private javax.swing.JTextField txfRemitenteSobre;
    private javax.swing.JTextField txfTelefono;
    private javax.swing.JTextField txtDescuentoTipoCliente;
    private javax.swing.JTextField txtImpuestoColones;
    private javax.swing.JTextField txtTotalImpuestoAPagar;
    // End of variables declaration//GEN-END:variables
}
